<a href="https://colab.research.google.com/github/biswasparajuli/python-march28/blob/master/Introduction_to_numpy_ds600.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy

The fundamental package for scientific computing with Python.

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering.

* It is used to create N-Dimensional Array.

The NumPy library contains multidimensional array and matrix data structures (you’ll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

# Installing Numpy

In [ ]:
!pip install numpy

# importing numpy

In [40]:
import numpy as np

In [39]:
np.__version__

'1.25.2'

# Creating array using numpy

An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

In [ ]:
# creating an empty array; array generally list bata banainxa

In [ ]:
x = np.array( [] )
x

array([], dtype=float64)

In [ ]:
x.dtype

dtype('float64')

In [ ]:
type(x)

numpy.ndarray

In [ ]:
# ndarray means n-dimensional array

# Creating 1D array

In [ ]:
x = np.array([55, 3, 22, 0, 9, 7, 5, 2])
x

array([55,  3, 22,  0,  9,  7,  5,  2])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.ndim # It is one dimensional array

1

In [ ]:
x.shape # array is of length 8; It is one dimensional array

(8,)

In [ ]:
len(x)  # array is of length 8

In [ ]:
x[4]

In [ ]:
x[7]

In [ ]:
x[1]

In [ ]:
x[-1]

In [ ]:
x[6]

In [ ]:
x[-2]

5

In [ ]:
x[8]

In [ ]:
x[3:6]

array([0, 9, 7])

In [ ]:
x[:3]

array([55,  3, 22])

In [ ]:
x[0:3:1]

array([55,  3, 22])

In [ ]:
x[0:3]

array([55,  3, 22])

In [ ]:
x[-4:]

array([9, 7, 5, 2])

In [ ]:
x[:-4]

array([55,  3, 22,  0])

# Difference between Numpy array and List

* List supports multiple datatype; however, array supports homogeneous datatype

* arrays are memory effecient than list

* arrays are faster than list

In [ ]:
data_list = [True, 0.2, 5, "hello"]

In [ ]:
data_list[0]

True

In [ ]:
type(data_list[0])

bool

In [ ]:
data_array = np.array(data_list)
data_array

array(['True', '0.2', '5', 'hello'], dtype='<U32')

In [ ]:
data_array[0]

'True'

In [ ]:
type(data_array[0])

numpy.str_

In [ ]:
# arrays are memory effecient

In [ ]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [ ]:
x.dtype

dtype('float64')

In [ ]:
x = np.zeros(5, dtype= np.int8)
x

array([0, 0, 0, 0, 0], dtype=int8)

In [ ]:
x = np.zeros(5, dtype= np.float16)
x

array([0., 0., 0., 0., 0.], dtype=float16)

In [ ]:
x = np.ones(3, dtype=np.int32)
x

array([1, 1, 1], dtype=int32)

In [ ]:
# arrays are faster than list because arrays are memory effecient

# .arange()

In [ ]:
list(range(0, 5)) # python

[0, 1, 2, 3, 4]

In [ ]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(15, 30, 3)  # .arange(start, stop, step)  # stop ko value print hudaina

array([15, 18, 21, 24, 27])

# linspace

In [ ]:
import numpy as np

In [ ]:
x = np.linspace(start=0, stop=1, num=5) # 0 deki 1 samma equal spacing ko 5 ota number ko array generate garne
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(start=10, stop=30, num=15)

array([10.        , 11.42857143, 12.85714286, 14.28571429, 15.71428571,
       17.14285714, 18.57142857, 20.        , 21.42857143, 22.85714286,
       24.28571429, 25.71428571, 27.14285714, 28.57142857, 30.        ])

# Concat and sorting array

In [ ]:
x = np.array([6, 5, 4])
y = np.array([5, 6, 2])

In [ ]:
[6, 5, 4] + [5, 6, 2] # concat

[6, 5, 4, 5, 6, 2]

In [ ]:
x + y # element wise addition; list ma jasari concat garna mildaina

array([11, 11,  6])

In [ ]:
np.concatenate([x,y])

array([6, 5, 4, 5, 6, 2])

In [ ]:
# sorting of array

In [ ]:
x = np.array([5, -1, 2, -3, 7, 4, -1])
x

array([ 5, -1,  2, -3,  7,  4, -1])

In [ ]:
np.sort(x) # ascending order

array([-3, -1, -1,  2,  4,  5,  7])

In [ ]:
np.flip(np.sort(x)) # descending

array([ 7,  5,  4,  2, -1, -1, -3])

# Broadcasting

In [ ]:
x = np.array([6, 3])

In [ ]:
2 * x # 2 broadcast hunxa array ma ra each element lai multiply garxa; vector lai scalar le multiply garda vector aauxa

array([12,  6])

In [ ]:
x * 2

array([12,  6])

In [ ]:
x + 2

array([8, 5])

# Vector operations

In [ ]:
x = np.array([6, 8, 4])
y = np.array([6, 2, 2])

In [ ]:
x + y

array([12, 10,  6])

In [ ]:
x - y

array([0, 6, 2])

In [ ]:
x ** y

array([46656,    64,    16])

# Generating Random numbers in numpy

In [34]:
np.random.randint(low=1, high=100)

48

In [35]:
np.random.seed(0) # seed >= 0
np.random.randint(low=1, high=100)

45

In [36]:
np.random.seed(0) # seed >= 0
np.random.randint(low=1, high=100, size=10)

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

# .any() vs .all()

In [ ]:
np.random.seed(42)
age = np.random.randint(low=1, high=10, size=5)
age

array([7, 4, 8, 5, 7])

In [ ]:
age > 5 # condition

array([ True, False,  True, False,  True])

In [ ]:
np.any(age>5)

True

In [ ]:
np.all(age>5)

False

In [ ]:
np.all(age>=4)

True

In [ ]:
age[age>5]

array([7, 8, 7])

In [ ]:
age

array([7, 4, 8, 5, 7])

In [ ]:
age[age>4 and age<8] # numpy ma logical operator use garna mildaina use bitwise instead

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
age[(age>4) & (age<8)]  # bitwise and (&) bitwise and use garda condition lai round bracket ma rakhnuparxa

array([7, 5, 7])

# 2D array or Matrix

In [ ]:
matrix = np.array( [ [1,2,3], [4,5,6], [7,8,9] ] )
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix.shape

(3, 3)

In [ ]:
matrix.ndim

2

# Indexing and slicing

In [ ]:
matrix[1, 2]

6

In [ ]:
matrix[0, 1]

2

In [ ]:
matrix[2, 0]

7

In [ ]:
matrix[2, 2]

9

In [ ]:
matrix[1, :]

array([4, 5, 6])

In [ ]:
matrix[2, :]

array([7, 8, 9])

In [ ]:
matrix[:, 1]

array([2, 5, 8])

In [ ]:
matrix[1:, 1:]

In [ ]:
matrix[:2, :]

In [ ]:
matrix[1:, :2]

Matrix Operation and Linear Algerbra in Numpy

In [1]:
import numpy as np

dot product / Matrix Multiplication

In [4]:
A = np.array([[1,2,3], [4,5,6]])
B= np.array([[7,8],[9,10],[11,12]])

In [5]:
A.shape

(2, 3)

In [6]:
B.shape

(3, 2)

In [8]:
output= np.dot(A,B)
output

array([[ 58,  64],
       [139, 154]])

# Singular Vs Non-Singular Matrix

* A singular matrix is a square matrix whose determinant is zero.
*  A non-singular matrix has a determinant that is not equal to zero.

In [10]:
c = np.linalg.det(output)
c

36.000000000000256

In [11]:
np.round(c)

36.0

Non- Singular matrix ko invers exist garxa

In [12]:
np.linalg.inv(output)

array([[ 4.27777778, -1.77777778],
       [-3.86111111,  1.61111111]])

Transpose

In [13]:
output.T

array([[ 58, 139],
       [ 64, 154]])

The axis argument in numpy: 2D axis = 0 is column-wise and axis = 1 means row-wise

In [14]:
x = np.array([[1,2,3],[4,5,6]])
x


array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
x.sum() # sum of array items

21

In [17]:
x.sum(axis = 0)

array([5, 7, 9])

In [18]:
x.sum(axis = 1)

array([ 6, 15])

In [20]:
x.max(axis= 1)

array([3, 6])

In [21]:
x.max(axis = 0)

array([4, 5, 6])

Reshape

In [23]:
x = np.array([66,3,77,45,88,5])
x

array([66,  3, 77, 45, 88,  5])

In [24]:
x.shape

(6,)

In [25]:
x.reshape(3,2) # reshaping in 2D array

array([[66,  3],
       [77, 45],
       [88,  5]])

In [26]:
x.reshape(2,3)

array([[66,  3, 77],
       [45, 88,  5]])

In [28]:
x.reshape(1,6) # row matrix


array([[66,  3, 77, 45, 88,  5]])

In [30]:
x.reshape(6,1) # column Matrix

array([[66],
       [ 3],
       [77],
       [45],
       [88],
       [ 5]])

<img src="https://d20khd7ddkh5ls.cloudfront.net/row_column_matrices.jpg">

In [43]:
np.random.seed(40)
x = np.random.randint(low=5, high = 10, size=7)
x

array([8, 5, 5, 7, 6, 9, 7])

In [44]:
x.reshape(1,-1) # row matrix

array([[8, 5, 5, 7, 6, 9, 7]])

In [45]:
x.reshape(-1,1)

array([[8],
       [5],
       [5],
       [7],
       [6],
       [9],
       [7]])

# RGB Images are in 3D

---




In [49]:
x = np.zeros((2,3,4))
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [50]:
x = np.zeros((2,3,4))
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])